# Generated by Django 4.1.4 on 2023-10-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(help_text='Может быть пустым, если используется named URL', max_length=100, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Именованный URL')),
                ('menu_name', models.CharField(max_length=50, verbose_name='Имя меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MenuLinks.menuitem')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
